#!/usr/bin/env python3
"""Generate a lightweight dashboard hub.

Output: pages/dashboard.md
The authoritative machine status remains pages/system_status.md.
"""

import os
import sqlite3
from pathlib import Path
import re

try:
    from scripts.time_utils import seoul_timestamp_seconds_str, seoul_today_str
except Exception:  # pragma: no cover
    from time_utils import seoul_timestamp_seconds_str, seoul_today_str  # type: ignore

BASE = Path(__file__).resolve().parent.parent
DB_PATH = BASE / 'data' / 'wiki.db'
DASHBOARD_MD = BASE / 'pages' / 'dashboard.md'
SYSTEM_STATUS_MD = BASE / 'pages' / 'system_status.md'
NEWS_DIR = BASE / 'news'

def get_db_stats():
    if not DB_PATH.exists():
        return {"urls": 0}

    try:
        conn = sqlite3.connect(DB_PATH)
        c = conn.cursor()
        c.execute("SELECT count(*) FROM seen_urls")
        count = c.fetchone()[0]
        conn.close()
        return {"urls": count}
    except (sqlite3.Error, OSError):
        return {"urls": "Error"}

def get_last_run_status():
    today = seoul_today_str()
    log_path = NEWS_DIR / f"{today}.md"

    if not log_path.exists():
        return "Not Run Yet", "Gray"

    content = log_path.read_text(encoding="utf-8")

    if re.search(r"^- 결과:\s*성공\s*$", content, flags=re.M):
        return "Success", "Green"
    if re.search(r"^- 결과:\s*실패\s*$", content, flags=re.M):
        return "Fail", "Red"
    if re.search(r"^- 결과:\s*부분성공\s*$", content, flags=re.M):
        return "Partial", "Yellow"
    if re.search(r"^- 결과:\s*진행중\s*$", content, flags=re.M):
        return "Running", "Yellow"

    return "Running/Unknown", "Yellow"


def get_system_status_snapshot() -> list[str]:
    if not SYSTEM_STATUS_MD.exists():
        return ["- system_status.md not generated yet"]
    out: list[str] = []
    for line in SYSTEM_STATUS_MD.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            out.append(f"- {line.removeprefix('## ')}")
        if len(out) >= 4:
            break
    return out or ["- system_status.md is present but empty"]

def main():
    db_stats = get_db_stats()
    run_status, run_color = get_last_run_status()
    now = seoul_timestamp_seconds_str()
    snapshot = "\n".join(get_system_status_snapshot())

    dashboard = f"""# Dashboard
> Last Refreshed: {now} (Asia/Seoul)

## Quick Status
| Metric | Status | Note |
| :--- | :--- | :--- |
| **Daily Update** | **{run_status}** | See `news/` for today |
| **Database** | {db_stats['urls']} URLs | `wiki.db` size: {os.path.getsize(DB_PATH) if DB_PATH.exists() else 0} bytes |
| **Machine Status** | See `system_status.md` | This page is a hub, not the source of truth |

## System Snapshot
{snapshot}

## Links
- 시스템 상태: [`pages/system_status.md`](system_status.md)
- 일일 리포트: [`pages/daily-report.md`](daily-report.md)
- 품질 리포트: [`pages/quality-report.md`](quality-report.md)
- 링크 건강검진: [`pages/link-health.md`](link-health.md)
- 공식 커버리지 감사: [`pages/official-coverage-audit.md`](official-coverage-audit.md)
- 타임라인: [`pages/timeline.md`](timeline.md)

---
*Generated by scripts/update_dashboard.py. Source of truth: scripts/wiki_score.py + scripts/check_automation_health.sh*
"""

    DASHBOARD_MD.write_text(dashboard, encoding='utf-8')
    print(f"Updated Dashboard: {DASHBOARD_MD}")

if __name__ == "__main__":
    main()
