#!/usr/bin/env python3
"""Generate System Status Dashboard.
- Output: pages/system_status.md
- Metrics:
  - Total URLs tracked (DB)
  - Last Update Time
  - Broken Links Count
  - Recent News Count
"""

import os
import sqlite3
from datetime import datetime
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DB_PATH = BASE / 'data' / 'wiki.db'
DASHBOARD_MD = BASE / 'pages' / 'system_status.md'
NEWS_DIR = BASE / 'news'

def get_db_stats():
    if not DB_PATH.exists():
        return {"urls": 0}

    try:
        conn = sqlite3.connect(DB_PATH)
        c = conn.cursor()
        c.execute("SELECT count(*) FROM seen_urls")
        count = c.fetchone()[0]
        conn.close()
        return {"urls": count}
    except (sqlite3.Error, OSError):
        return {"urls": "Error"}

def get_last_run_status():
    # Check today's news log
    today = datetime.now().strftime("%Y-%m-%d")
    log_path = NEWS_DIR / f"{today}.md"

    if not log_path.exists():
        return "Not Run Yet", "Gray"

    content = log_path.read_text(encoding='utf-8')
    if "결과: 성공" in content:
        return "Success", "Green"
    elif "결과: 실패" in content:
        return "Fail", "Red"
    return "Running/Unknown", "Yellow"

def main():
    db_stats = get_db_stats()
    run_status, run_color = get_last_run_status()
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Markdown Dashboard
    dashboard = f"""# 🖥️ System Status Dashboard
> Last Refreshed: {now}

## 🚦 Automation Health
| Metric | Status | Note |
| :--- | :--- | :--- |
| **Daily Update** | **{run_status}** | Check `news/` for details |
| **Database** | {db_stats['urls']} URLs | `wiki.db` size: {os.path.getsize(DB_PATH) if DB_PATH.exists() else 0} bytes |
| **Config** | Active | `config.yaml` loaded |

## 📊 Modules
- **News Collector**: Active (Google RSS)
- **Schedule Estimator**: Active
- **Profile Updater**: Active (Context Aware)
- **Visuals**: Active (Mermaid Timeline)

## 🔗 Quick Actions
- [View Daily Log](../news/)
- [View Timeline](timeline.md)
- [View Link Health](link-health.md)

---
*Generated by scripts/update_dashboard.py*
"""

    DASHBOARD_MD.write_text(dashboard, encoding='utf-8')
    print(f"Updated Dashboard: {DASHBOARD_MD}")

if __name__ == "__main__":
    main()
